title: Personal Blog?!
description: DevOps,Developer,Insist with Open
author: Mreza Molla Salehi
avatar: /logo.png
email: info@mrsalehi.info

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: mrsalehi6
  card: summary
logo: logo.png
social:
  name: Mreza Molla Salehi
  links:
    - https://twitter.com/mrsalehi6
    - https://mrsalehi.info
    - https://github.com/mm3906078
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
